import { Drop, IntakeSubmission, Order, Product } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    sku: 'ELC-MK-102',
    title: 'Electric Mini Kettle 1.5L',
    slug: 'electric-mini-kettle-1-5l',
    description:
      'Fast boiling 1.5-liter electric kettle with auto shutdown. Perfect for quick noodles, tea, and late-night hostel study sessions. Inspected and descaled.',
    categoryId: 'electronics',
    images: [
      'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f6?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 850,
    acquisitionPrice: 500,
    referencePrice: 1600,
    condition: 'Excellent',
    conditionDetails: 'Clean heating element, minor hairline scratch on base handle. Fully functional.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: true,
    dropId: 'drop-friday-tech',
    dropName: 'Friday Tech Drop',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'prod-102',
    sku: 'TXT-CAL-204',
    title: 'Casio Scientific Calculator FX-991ES',
    slug: 'casio-scientific-calculator-fx-991es',
    description:
      'Dual power (solar + battery) advanced scientific calculator. Essential for engineering, science, and math courses. Includes protective slide-on hard case.',
    categoryId: 'textbooks',
    images: [
      'https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48a?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 600,
    acquisitionPrice: 350,
    referencePrice: 1400,
    condition: 'Good',
    conditionDetails: 'All keys click crisply. Screen is crystal clear with no dead pixels.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: true,
    dropId: 'drop-exam-season',
    dropName: 'Exam Season Essentials',
    createdAt: '2026-08-16T14:30:00Z',
    updatedAt: '2026-08-16T14:30:00Z',
  },
  {
    id: 'prod-103',
    sku: 'FSH-DJ-301',
    title: 'Vintage Oversized Denim Jacket',
    slug: 'vintage-oversized-denim-jacket',
    description:
      'Classic medium wash heavyweight cotton denim jacket. Relaxed drop-shoulder fit. Thoroughly washed and sanitized by MiThrift.',
    categoryId: 'fashion',
    images: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1543076447-215ad9ba6923?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 1200,
    acquisitionPrice: 800,
    referencePrice: 2800,
    condition: 'Excellent',
    conditionDetails: 'Size Medium/Large unisex fit. No tears, stains, or fraying.',
    status: 'AVAILABLE',
    inventoryType: 'CONSIGNMENT',
    consignorId: 'cns-101',
    consignorName: 'Mercy W.',
    consignorPhone: '+254722998877',
    commissionRate: 0.25,
    isFeatured: true,
    dropId: 'drop-streetwear',
    dropName: 'Streetwear Drop',
    createdAt: '2026-08-17T09:15:00Z',
    updatedAt: '2026-08-17T09:15:00Z',
  },
  {
    id: 'prod-104',
    sku: 'HME-SL-118',
    title: 'Dimmable LED Desk Study Lamp',
    slug: 'dimmable-led-desk-study-lamp',
    description:
      'Flexible gooseneck study lamp with 3 color modes and USB charging port on the base. Compact base fits small hostel desks.',
    categoryId: 'hostel-essentials',
    images: [
      'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 750,
    acquisitionPrice: 400,
    referencePrice: 1500,
    condition: 'Like New',
    conditionDetails: 'Used for only one semester. Includes original micro-USB cable.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: true,
    dropId: 'drop-friday-tech',
    dropName: 'Friday Tech Drop',
    createdAt: '2026-08-18T11:00:00Z',
    updatedAt: '2026-08-18T11:00:00Z',
  },
  {
    id: 'prod-105',
    sku: 'APP-MW-502',
    title: 'Compact Digital Microwave 20L',
    slug: 'compact-digital-microwave-20l',
    description:
      '700W 20L digital solo microwave with glass turntable. Super fast heating for hostel meals. Deep cleaned and sanitized.',
    categoryId: 'appliances',
    images: [
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 3800,
    acquisitionPrice: 2500,
    referencePrice: 7500,
    condition: 'Excellent',
    conditionDetails: 'Interior cavity immaculate. Digital timer and turntable work smoothly.',
    status: 'RESERVED',
    reservedAt: '2026-08-20T12:00:00Z',
    reservedByPhone: '+254700112233',
    inventoryType: 'CONSIGNMENT',
    consignorId: 'cns-102',
    consignorName: 'Brian K.',
    consignorPhone: '+254711334455',
    commissionRate: 0.25,
    isFeatured: false,
    createdAt: '2026-08-14T08:30:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'prod-106',
    sku: 'ELC-HP-801',
    title: 'Wireless Active Noise-Cancelling Headphones',
    slug: 'wireless-active-noise-cancelling-headphones',
    description:
      'Over-ear Bluetooth headphones with plush earcups and active noise isolation. Up to 25 hours battery life for uninterrupted study sessions in noisy hostels.',
    categoryId: 'electronics',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 1450,
    acquisitionPrice: 900,
    referencePrice: 3200,
    condition: 'Like New',
    conditionDetails: 'Pristine cushion pads. Comes with 3.5mm aux cable & charging cable.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: true,
    dropId: 'drop-friday-tech',
    dropName: 'Friday Tech Drop',
    createdAt: '2026-08-19T15:20:00Z',
    updatedAt: '2026-08-19T15:20:00Z',
  },
  {
    id: 'prod-107',
    sku: 'STR-HD-405',
    title: 'Heavyweight Fleece Graphic Hoodie',
    slug: 'heavyweight-fleece-graphic-hoodie',
    description:
      '400GSM thick cotton fleece sweater with kangaroo pocket and subtle chest print. Warm lining for chilly morning lectures.',
    categoryId: 'streetwear',
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 950,
    acquisitionPrice: 600,
    referencePrice: 2200,
    condition: 'Excellent',
    conditionDetails: 'Size L fit. Minimal wash wear. Ribbed cuffs firm.',
    status: 'SOLD',
    soldAt: '2026-08-19T18:45:00Z',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: false,
    dropId: 'drop-streetwear',
    dropName: 'Streetwear Drop',
    createdAt: '2026-08-12T16:00:00Z',
    updatedAt: '2026-08-19T18:45:00Z',
  },
  {
    id: 'prod-108',
    sku: 'TXT-CH-109',
    title: 'Organic Chemistry (8th Edition - Wade)',
    slug: 'organic-chemistry-8th-edition-wade',
    description:
      'Comprehensive university textbook for pre-med and chemistry students. Clear reaction mechanisms and chapter practice problems.',
    categoryId: 'textbooks',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 1100,
    acquisitionPrice: 700,
    referencePrice: 3500,
    condition: 'Good',
    conditionDetails: 'Light yellow highlighter on chapters 3 & 5. Binding remains sturdy.',
    status: 'AVAILABLE',
    inventoryType: 'CONSIGNMENT',
    consignorId: 'cns-103',
    consignorName: 'David N.',
    consignorPhone: '+254799887766',
    commissionRate: 0.25,
    isFeatured: false,
    createdAt: '2026-08-18T10:10:00Z',
    updatedAt: '2026-08-18T10:10:00Z',
  },
  {
    id: 'prod-109',
    sku: 'APP-HP-203',
    title: 'Single Burner Electric Hot Plate',
    slug: 'single-burner-electric-hot-plate',
    description:
      '1000W cast-iron heating hot plate with adjustable thermostat dial. Non-slip rubber feet.',
    categoryId: 'appliances',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 1250,
    acquisitionPrice: 800,
    referencePrice: 2400,
    condition: 'Like New',
    conditionDetails: 'Fast heating coil tested by MiThrift staff.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: false,
    createdAt: '2026-08-19T09:40:00Z',
    updatedAt: '2026-08-19T09:40:00Z',
  },
  {
    id: 'prod-110',
    sku: 'FUR-SC-601',
    title: 'Ergonomic Mesh Study Chair',
    slug: 'ergonomic-mesh-study-chair',
    description:
      'Breathable mesh high-back desk chair with lumbar support and pneumatic height adjustment knob.',
    categoryId: 'furniture',
    images: [
      'https://images.unsplash.com/photo-1580481072645-022f9a6d8310?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 2400,
    acquisitionPrice: 1500,
    referencePrice: 5800,
    condition: 'Good',
    conditionDetails: 'Smooth casters, hydraulic lift holds weight firm.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: false,
    createdAt: '2026-08-16T11:25:00Z',
    updatedAt: '2026-08-16T11:25:00Z',
  },
  {
    id: 'prod-111',
    sku: 'ACC-BP-712',
    title: 'Water-Resistant Canvas Laptop Backpack 15.6"',
    slug: 'water-resistant-canvas-laptop-backpack-15-6',
    description:
      'Multi-compartment vintage canvas rucksack with padded 15.6" laptop sleeve and side water bottle pockets.',
    categoryId: 'accessories-jewelry',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 1150,
    acquisitionPrice: 700,
    referencePrice: 2500,
    condition: 'Excellent',
    conditionDetails: 'Zippers smooth, inner lining intact, clean shoulder straps.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: true,
    createdAt: '2026-08-20T08:15:00Z',
    updatedAt: '2026-08-20T08:15:00Z',
  },
  {
    id: 'prod-112',
    sku: 'SPT-WB-330',
    title: 'Insulated Stainless Steel Water Flask 1L',
    slug: 'insulated-stainless-steel-water-flask-1l',
    description:
      'Double-wall vacuum insulated flask keeps drinks ice-cold for 24 hours or hot for 12 hours.',
    categoryId: 'sports-outdoor',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=800&auto=format&fit=crop',
    ],
    sellingPrice: 450,
    acquisitionPrice: 250,
    referencePrice: 1200,
    condition: 'Like New',
    conditionDetails: 'Sterilized stainless steel interior. Zero leaks.',
    status: 'AVAILABLE',
    inventoryType: 'DIRECT_BUYOUT',
    isFeatured: false,
    createdAt: '2026-08-20T09:00:00Z',
    updatedAt: '2026-08-20T09:00:00Z',
  },
];

export const INITIAL_DROPS: Drop[] = [
  {
    id: 'drop-friday-tech',
    name: 'Friday Tech & Hostel Drop',
    slug: 'friday-tech-hostel-drop',
    tagline: '30 Tech & Hostel Essentials',
    description:
      'Curated drop containing kettles, noise-cancelling headphones, desk lamps, extension cords, and hostel appliances.',
    coverImage:
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop',
    releaseDate: '2026-08-21',
    releaseTime: '18:00',
    status: 'LIVE',
    productIds: ['prod-101', 'prod-104', 'prod-106'],
    isFeatured: true,
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'drop-streetwear',
    name: 'Streetwear & Vintage Drop',
    slug: 'streetwear-vintage-drop',
    tagline: 'Curated Student Fashion & 1-of-1 Pieces',
    description:
      'Handpicked vintage denim, oversized graphic hoodies, varsity jackets, and streetwear accessories.',
    coverImage:
      'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=1200&auto=format&fit=crop',
    releaseDate: '2026-08-23',
    releaseTime: '19:00',
    status: 'UPCOMING',
    productIds: ['prod-103', 'prod-107'],
    isFeatured: true,
    createdAt: '2026-08-16T12:00:00Z',
  },
  {
    id: 'drop-exam-season',
    name: 'Exam Season Essentials',
    slug: 'exam-season-essentials',
    tagline: 'Calculators, Textbooks & Study Aids',
    description:
      'Get ready for exams with scientific calculators, reference textbooks, eye-comfort lamps, and quiet study accessories.',
    coverImage:
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1200&auto=format&fit=crop',
    releaseDate: '2026-08-25',
    releaseTime: '16:00',
    status: 'UPCOMING',
    productIds: ['prod-102', 'prod-108'],
    isFeatured: false,
    createdAt: '2026-08-17T08:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'MITH-8421',
    customerName: 'Kevin M.',
    customerPhone: '+254700112233',
    customerCampus: 'Main Campus',
    productId: 'prod-105',
    productSku: 'APP-MW-502',
    productTitle: 'Compact Digital Microwave 20L',
    productPrice: 3800,
    pickupLocationId: 'loc-library',
    pickupLocationName: 'Library Gate',
    status: 'READY_FOR_PICKUP',
    paymentStatus: 'UNPAID',
    notes: 'Requested pickup around 4 PM.',
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-08-20T13:30:00Z',
  },
  {
    id: 'MITH-7319',
    customerName: 'Amina J.',
    customerPhone: '+254711998877',
    customerCampus: 'Main Campus',
    productId: 'prod-107',
    productSku: 'STR-HD-405',
    productTitle: 'Heavyweight Fleece Graphic Hoodie',
    productPrice: 950,
    pickupLocationId: 'loc-center',
    pickupLocationName: 'Student Center',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    createdAt: '2026-08-19T17:30:00Z',
    updatedAt: '2026-08-19T18:45:00Z',
  },
];

export const INITIAL_INTAKES: IntakeSubmission[] = [
  {
    id: 'sub-201',
    studentName: 'Faith W.',
    studentPhone: '+254712001122',
    campus: 'Main Campus',
    categoryId: 'appliances',
    itemTitle: 'Russell Hobbs Sandwich Press',
    description: '2-slice non-stick electric toaster press. Works great, moving out of hostel.',
    condition: 'Excellent',
    askingPrice: 1000,
    preferredModel: 'DIRECT_BUYOUT',
    photoUrls: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=600&auto=format&fit=crop',
    ],
    status: 'PENDING_REVIEW',
    createdAt: '2026-08-20T11:45:00Z',
  },
];
